version: '3.8'

services:
  spring-app:
    image: zack-back:latest
    ports:
      - "8443:8443"
    volumes:
      - arquivos-data:/app/arquivos

  spa-app:
    build:
      context: ./zack-front
      dockerfile: Dockerfile
    ports:
      - "8081:80"

volumes:
  arquivos-data:
    driver: local
