version: '3.8'

services:
  spring-app:
    image: zack-back:latest
    ports:
      - "8080:8080"
    volumes:
      - arquivos-data:/app/arquivos

  spa-app:
    build:
      context: ./zack-front
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8082:80"
      - "8443:443"
    volumes:
      - ./zack-front//nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - spa-app
      - spring-app

volumes:
  arquivos-data:
    driver: local
